directory: ~/Music
library: ~/Music/.beets/library.blb
import:
  copy: yes
  write: yes
  resume: ask
  log: beetslog.txt
  languages: 'en'
art_filename: albumart
threaded: yes
color: yes

match:
  preferred:
    media: ['CD', 'Digital Media|File', 'Vinyl']
  max_rec:
    mediums: low
    tracks: medium

paths:
  default: $firstartist/%asciify{$album%aunique{}} %if{$restartist,performed by $restartist} ($year)/%if{$multidisc,$disc}-$track - $title
  #default: $albumartist/$album%aunique{} ($year)/%if{$multidisc,Disc $disc/}$track - $title
  singleton: Singles/$artist/$title
  comp: Compilations/$album%aunique{} ($year)/%if{$multidisc,Disc $disc/}$track - $title
  albumtype:soundtrack: Soundtracks/$album%aunique{} ($year)/%if{$multidisc,Disc $disc/}$track - $title

plugins: discogs fetchart embedart lastgenre lastimport mbsync mpdupdate info inline

item_fields:
  multidisc: 1 if disctotal > 1 else 0
  firstartist: albumartist.split(';')[0]
  restartist: |
    parts = albumartist.split(';', 1)
    if len(parts) > 1:
      return parts[1]
    else:
      return ''

fetchart:
  cautious: true
  cover_names: front back

lastgenre:
  auto: yes
  count: 3

lastfm:
  user: sondr3

mpd:
  host: 127.0.0.1
  port: 6600
